# Generated by Django 2.0 on 2017-12-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
