# Generated by Django 2.0 on 2017-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
